student_count = 25
puts "Dave"
puts "Eddie"
puts "Catharina"
puts "Igor"
puts "Marco"
puts "Lisa"
puts "Michiel"
puts "Jean"
puts "Nicola"
puts "Jennie"
puts "Iona"
puts "Nikesh"
puts "Chloe"
puts "Toan"
puts "Jamie"
puts "Peter"
puts "Talal"
puts "Charlie"
puts "Charlotte"
puts "Thomas"
puts "Zoe"
puts "Hannah"
puts "Joe"
puts "Alex"
puts "Jeremy"

puts "Overall, we have #{student_count} great students" 
